curated_keywords = [
    (
        "learning from demonstration",  # not a detected keyword
        "inverse reinforcement learning",
        "expert demonstrations",
        "apprenticeship learning",
        "imitation",
        "imitation learning",
        "demonstrated trajectories",
        "demonstration",
        "demonstrations",
        "human demonstration",
        "helicopters",
        "autonomous helicopter control",
    ),
    ("attention"),
    ("cognitive sciences", "cognitive science"),
    (
        "computer vision",
        "visual perception",
        "vision",
        "image classification",
        "visual features",
        "visual feedback",
        "visual information",
        "perception",
        "pixels",
        "object detection",
        "object localization",
        "object recognition",
        "object segmentation",
        "raw images",
    ),
    ("contact dynamics", "contact",),
    (
        "control",
        "control theory",
        "control algorithms",
        "control policies",
        "control problems",
        "control signals",
        "control systems",
        "controller",
        "controllers",
        "continuous control",
        "feedback",
        "feedback control",
        "robot control",
        "robotic control",
    ),
    (
        "convolutional neural networks",
        "convolutional networks",
        "deep convolutional neural networks",
    ),
    ("dynamic programming"),
    (
        "dynamical systems",
        "dynamic systems",
        "dynamics",
        "dynamics models",
        "nonlinear dynamical systems",
        "system dynamics",
        "robot dynamics",
    ),
    ("evolution", "evolutionary computation",),
    ("genetic algorithms"),
    ("gaussian processes", "gaussian", "gaussian distributions", "gaussian noise",),
    (
        "gradient methods",
        "gradient",
        "gradients",
        "gradient descent",
        "stochastic gradient descent",
    ),
    ("graphs"),
    (
        "grasping",  # not a real keyword
        "grasping objects",
        "grasping points",
        "grasps",
        "robotic grasping",
    ),
    ("humanoid robotics", "humanoid robot", "humanoid robots",),
    ("locomotion"),
    (
        "machine learning",
        "machine learning methods",
        "machine learning research",
        "machine learning techniques",
    ),
    ("markov", "hidden markov models", "markov decision processes",),
    ("mobile robots", "navigation", "localization",),
    (
        "motor learning",
        "motor skills",
        "motor commands",
        "motor control",
        "motor primitives",
        "deep visuomotor policies",
        "sensorimotor control",
    ),
    (
        "neural networks",
        "neural network",
        "neural network policies",
        "deep neural networks",
        "artificial neural networks",
        "deep learning",
        "deep networks",
    ),
    ("nonlinear systems", "nonlinear dynamical systems",),
    ("online learning"),
    (
        "optimal control",
        "optimal control problems",
        "model predictive control",
        "stochastic optimal control",
    ),
    (
        "trajectory optimization",
        "robot trajectory optimization",
        "guided policy search",
    ),
    (
        "planning",
        "plans",
        "motion planning",
        "trajectory planning",
        "movement primitives",
    ),
    (
        "policy gradient",
        "policy gradient methods",
        "policy gradient reinforcement",
        "policy gradient reinforcement learning",
        "policy gradients",
        "trust region policy optimization",
    ),
    (
        "probabilistic models",
        "probability",
        "probabilistic",
        "probabilistic inference",
        "probability distributions",
        "bayes",
        "bayesian",
        "bayesian inference",
        "covariance",
        "variance",
        "monte carlo",
    ),
    ("legged robots", "quadruped robots",),
    ("real data", "real images", "real robots", "physical systems",),
    ("recurrent neural networks"),
    (
        "reinforcement learning",
        "reinforcement",
        "reinforcement learning algorithms",
        "reinforcement learning methods",
        "reinforcement learning policy search methods",
        "deep reinforcement",
        "deep reinforcement learning",
        "agents",
        "rl algorithms",
        "rl methods",
        "q learning",
        "barto",
        "sutton",
    ),
    (
        "policy learning",
        "policy",
        "policies",
        "policy improvement",
        "policy invariance",
        "policy iteration",
        "policy optimization",
        "policy search",
        "policy search methods",
        "covariant policy search",
    ),
    ("hierarchical reinforcement learning"),
    (
        "reward functions",
        "reward",
        "reward function",
        "rewards",
        "a reward function",
        "expected reward",
        "delayed rewards",
        "sparse rewards",
        "advantage",
    ),
    (
        "robot manipulators",
        "robot manipulation",
        "robotic manipulation",
        "manipulation",
        "a robot arm",
        "joint angles",
        "joint space",
    ),
    ("state estimation", "kalman",),
    (
        "supervised learning",
        "supervised learning methods",
        "regression",
        "classification",
    ),
    (
        "unsupervised learning",
        "representation",
        "representations",
        "deep generative models",
    ),
    (
        "value functions",
        "value function",
        "value function approximation",
        "value iteration",
    ),
]
